name: massai mark park 01 compose dockerhub multiple

on:
   workflow_dispatch
 
jobs:
  build:
      name: build JAR
      runs-on: ubuntu-22.04

      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: check docker compose version
          run: docker compose version

        - name: build with docker compose
          run: docker compose build

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-22.04
    steps:   
        - name: Checkout Code
          uses: actions/checkout@v4
          
        - name: run with docker compose
          run: |
            docker compose up -d 
            sleep 30

            docker compose ps
            docker compose logs

        - name: run automated test #1
          run: |
            curl http://localhost:8080 || exit 1

        - name: run automated test #1
          run: |
            curl http://localhost:8080/images || exit 1

        - name: run automated test #1
          run: |
            curl http://localhost:8080/animal || exit 1
          

