name: massai mark park 01 docker ec2

on:
  workflow_dispatch

env:
  DOCKER_USERNAME: soosoomon
  IMAGE_NAME: massai_mara
  IMAGE_TAG: v${{ github.run_number }}
  HOSTNAME: 43.201.150.221
  USERNAME: ubuntu

jobs:
  build_image:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          platforms: linux/amd64
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Check built image
        run: docker image ls

      - name: Save Docker image
        run: docker save ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} > image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  hub_push:
    needs: build_image
    runs-on: ubuntu-22.04

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load < image.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Logout from Docker Hub
        if: always()
        run: docker logout

  upload_files:
    needs: hub_push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload docker-compose.yaml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOSTNAME }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.EC2_PRIVATEKEY }}
          port: 22
          source: "compose-multijobs.yaml"
          target: "/home/${{ env.USERNAME }}"

      - name: Upload application.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOSTNAME }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.EC2_PRIVATEKEY }}
          port: 22
          source: "application.yml"
          target: "/home/${{ env.USERNAME }}"

  run_test:
    needs: upload_files
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOSTNAME }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.EC2_PRIVATEKEY }}
          port: 22
          script: |
            docker compose -f ./compose-multijobs.yaml up -d
            sleep 30
            docker compose ps
            docker compose logs